#!/bin/bash
#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=scrape_loc
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=04:00:00
#SBATCH --output=jobs/outputs/scrape_loc.log

module purge
module load 2025
module load Anaconda3/2025.06-1

cd /scratch-shared/pnair/Project_AI/
source activate streetview_pnair
export PYTHONNOUSERSITE=1

python scripts/data_collection/scrape_lm_async.py


