#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=test
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:00:00
#SBATCH --output=jobs/outputs/test_script.log

module purge
module load 2025
module load Anaconda3/2025.06-1

source activate streetview_pnair
export PYTHONNOUSERSITE=1
export PYTHONPATH=/scratch-shared/pnair/Project_AI:$PYTHONPATH
#python scripts/tests/export_dataset_to_csv.py --output dataset_export_thailand.csv --country "Thailand" --require-coordinates 
#python src/dataset.py
#python geodata.py
python src/models/baseline.py --country "India"