#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=viz_stage0_stage1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --time=02:00:00
#SBATCH --output=jobs/outputs/visualization/viz_stage0_stage1.log

module purge
module load 2025
module load Anaconda3/2025.06-1

cd /scratch-shared/pnair/Project_AI/
source activate streetview_pnair
export PYTHONNOUSERSITE=1
export PYTHONPATH=/scratch-shared/pnair/Project_AI:$PYTHONPATH

python scripts/analysis/visualize_stage0_stage1.py \
    --stage0_checkpoint /scratch-shared/pnair/Project_AI/results/stage0-prototype/geolocal_StreetCLIP/2025-12-24_09-29-59/checkpoints/best_model_stage0.pt \
    --stage1_checkpoint /scratch-shared/pnair/Project_AI/results/stage1-prototype/geolocal_StreetCLIP/2025-12-24_19-10-45/checkpoints/best_model_stage1.pt \
    --all_visualizations \
    --batch_size 128 \
    --num_workers 4

